import { defineConfig, type Plugin } from 'vite';

/**
 * Emit a service worker whose precache list carries the real content hashes of
 * this build. Written as a plugin rather than a static file because Vite hashes
 * the bundle filename, and a hand-written list would go stale on every build.
 *
 * Strategy:
 *   navigations  → network-first. index.html is the one file Vite does NOT
 *                  hash, so cache-first would pin a stale build forever.
 *   assets/*     → cache-first. Content-hashed, so a hit is always correct.
 *   everything   → falls back to the cache when offline.
 */
function serviceWorkerPlugin(): Plugin {
  return {
    name: 'hvv-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle).map((f) => `./${f}`);
      const precache = ['./', './index.html', './manifest.webmanifest', ...assets];
      // Cache name changes whenever the payload does, which is what evicts the
      // previous build instead of serving it forever.
      const version = precache.join('|').length.toString(36) + '-' + assets.join('|').length.toString(36);

      const sw = `/* Generated by vite.config.ts — do not edit. */
const CACHE = 'hvv-${version}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: fresh if we can, cached if we cannot.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match('./index.html'))),
    );
    return;
  }

  // Hashed assets: cache-first.
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      });
    }),
  );
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: sw });
    },
  };
}

export default defineConfig({
  // Relative so the same bundle works from a project subpath (GitHub Pages
  // serves at /<repo>/), from a custom scheme in a native shell, and from a
  // plain server. See docs/NATIVE.md.
  base: './',
  plugins: [serviceWorkerPlugin()],
  server: { host: true, port: 5173 },
  build: {
    target: 'es2022',
    outDir: 'dist',
    assetsInlineLimit: 0,
  },
});
