import type { HeroDef, HeroId } from '../sim/types';

/**
 * The hero roster — "plants", in the genre's terms.
 *
 * These are original characters written as loving archetype homages. No
 * trademarked names, logos, or likenesses are used anywhere in this project;
 * every emblem is drawn procedurally from the abstract glyphs in
 * src/render/emblems.ts.
 */
export const HEROES: HeroDef[] = [
  /* ---------------------------------------------------------------- *
   * Producers
   * ---------------------------------------------------------------- */
  {
    id: 'solaris',
    name: 'Solaris',
    tagline: 'Splits the atom, pays the bills.',
    universe: 'metro',
    role: 'producer',
    cost: 50,
    recharge: 5,
    hp: 300,
    attack: { interval: 8.5, produces: { resource: 'solar', amount: 25 } },
    ultimate: {
      id: 'solar_flare',
      name: 'Solar Flare',
      description: 'Vents a full corona: +150 solar at once.',
      duration: 1.6,
    },
    art: {
      primary: '#f4c542',
      secondary: '#e2632a',
      accent: '#fff3b0',
      skin: '#ffd9a0',
      emblem: 'sun',
      head: 'aura',
      glow: '#ffcf4d',
    },
  },
  {
    id: 'sunforge',
    name: 'Sunforge',
    tagline: 'Two cores. Double the payroll.',
    universe: 'metro',
    role: 'producer',
    cost: 150,
    recharge: 20,
    hp: 300,
    attack: { interval: 8.5, produces: { resource: 'solar', amount: 50 } },
    ultimate: {
      id: 'solar_flare',
      name: 'Twin Corona',
      description: 'Vents both cores: +300 solar at once.',
      duration: 1.6,
    },
    art: {
      primary: '#ffb02e',
      secondary: '#ff6b2c',
      accent: '#fff6c9',
      skin: '#ffd9a0',
      emblem: 'sun',
      head: 'aura',
      glow: '#ffb02e',
      scale: 1.06,
    },
  },

  /* ---------------------------------------------------------------- *
   * Defenders
   * ---------------------------------------------------------------- */
  {
    id: 'bulwark',
    name: 'Bulwark',
    tagline: 'Unbreakable skin, unshakeable shift schedule.',
    universe: 'street',
    role: 'defender',
    cost: 50,
    recharge: 20,
    hp: 4000,
    ultimate: {
      id: 'unbreakable',
      name: 'Unbreakable',
      description: 'Invulnerable for 10s and knocks back everything it touches.',
      duration: 10,
    },
    art: {
      primary: '#c9a227',
      secondary: '#6b4f1d',
      accent: '#ffe9a8',
      skin: '#8d5524',
      emblem: 'fist',
      head: 'bare',
      glow: '#ffd76a',
      scale: 1.05,
    },
  },
  {
    id: 'adamant',
    name: 'Adamant',
    tagline: 'It is clobbering hour, every hour.',
    universe: 'street',
    role: 'defender',
    cost: 125,
    recharge: 30,
    hp: 8000,
    tall: true,
    ultimate: {
      id: 'quake_slam',
      name: 'Quake Slam',
      description: 'Slams the lane: heavy damage and a full-lane shove.',
      duration: 2,
    },
    art: {
      primary: '#e0863a',
      secondary: '#8c4a1c',
      accent: '#ffd9a0',
      skin: '#e0863a',
      emblem: 'none',
      head: 'bare',
      glow: '#ff9d4d',
      scale: 1.18,
    },
  },

  /* ---------------------------------------------------------------- *
   * Core shooters
   * ---------------------------------------------------------------- */
  {
    id: 'bluebolt',
    name: 'Bluebolt',
    tagline: 'Alien tech, teenage attitude.',
    universe: 'metro',
    role: 'shooter',
    cost: 100,
    recharge: 5,
    hp: 300,
    attack: {
      interval: 1.4,
      requiresTarget: true,
      projectile: { kind: 'bolt', damage: 20, speed: 9, pierce: 1 },
    },
    ultimate: {
      id: 'barrage',
      name: 'Plasma Barrage',
      description: 'Empties the cannon: 40 rapid bolts down the lane.',
      duration: 3.2,
    },
    art: {
      primary: '#1e6fd9',
      secondary: '#0b2f66',
      accent: '#7fd4ff',
      skin: '#1e6fd9',
      emblem: 'atom',
      head: 'helm',
      glow: '#4fc3ff',
    },
  },
  {
    id: 'frostbane',
    name: 'Frostbane',
    tagline: 'Room temperature is a suggestion.',
    universe: 'street',
    role: 'shooter',
    cost: 175,
    recharge: 7,
    hp: 300,
    attack: {
      interval: 1.5,
      requiresTarget: true,
      projectile: {
        kind: 'frost',
        damage: 20,
        speed: 8.5,
        pierce: 1,
        effects: [{ type: 'slow', duration: 5, power: 0.5 }],
      },
    },
    ultimate: {
      id: 'deep_freeze',
      name: 'Absolute Zero',
      description: 'Flash-freezes every villain on the board for 6 seconds.',
      duration: 2.4,
    },
    art: {
      primary: '#8fd8ff',
      secondary: '#2a6f9e',
      accent: '#eaffff',
      skin: '#cfeeff',
      emblem: 'diamond',
      head: 'bare',
      glow: '#9fe8ff',
    },
  },
  {
    id: 'trickshot',
    name: 'Trickshot',
    tagline: 'Never misses. Ask him about it. He will tell you.',
    universe: 'street',
    role: 'shooter',
    cost: 175,
    recharge: 8,
    hp: 300,
    attack: {
      interval: 1.7,
      requiresTarget: true,
      laneSpread: 1,
      projectile: { kind: 'arrow', damage: 18, speed: 11, pierce: 2 },
    },
    ultimate: {
      id: 'arrow_storm',
      name: 'Arrow Storm',
      description: 'Rains 60 arrows across the right half of the board.',
      duration: 3.5,
    },
    art: {
      primary: '#2e8b3d',
      secondary: '#14421f',
      accent: '#c8f7a0',
      skin: '#e8b48c',
      emblem: 'arrow',
      head: 'hood',
      glow: '#7cf07c',
    },
  },
  {
    id: 'websnap',
    name: 'Websnap',
    tagline: 'Friendly. Neighbourhood. Extremely annoying to villains.',
    universe: 'street',
    role: 'shooter',
    cost: 175,
    recharge: 8,
    hp: 320,
    attack: {
      interval: 1.6,
      requiresTarget: true,
      hits: 'both',
      projectile: {
        kind: 'web',
        damage: 14,
        speed: 10,
        pierce: 1,
        hits: 'both',
        effects: [{ type: 'slow', duration: 4, power: 0.45 }],
      },
    },
    ultimate: {
      id: 'web_lane',
      name: 'Full Spread',
      description: 'Webs the entire lane, rooting everything in it for 7 seconds.',
      duration: 2,
    },
    art: {
      primary: '#c62828',
      secondary: '#1b3a8f',
      accent: '#ffffff',
      skin: '#c62828',
      emblem: 'web',
      head: 'mask',
      glow: '#ff6b6b',
    },
  },
  {
    id: 'voltaic',
    name: 'Voltaic',
    tagline: 'Half machine. All uptime.',
    universe: 'metro',
    role: 'shooter',
    cost: 200,
    recharge: 10,
    hp: 400,
    attack: {
      interval: 1.3,
      requiresTarget: true,
      hits: 'both',
      projectile: {
        kind: 'spark',
        damage: 24,
        speed: 12,
        pierce: 2,
        hits: 'both',
        effects: [{ type: 'stun', duration: 0.35 }],
      },
    },
    ultimate: {
      id: 'overload',
      name: 'Sonic Cannon',
      description: 'A sustained blast that shreds and staggers the whole lane.',
      duration: 3,
    },
    art: {
      primary: '#9aa7b4',
      secondary: '#2b3a4a',
      accent: '#ff3d3d',
      skin: '#5a3a2a',
      emblem: 'bolt',
      head: 'visor',
      glow: '#6be3ff',
    },
  },
  {
    id: 'vanguard',
    name: 'Vanguard',
    tagline: 'Out of time, never out of position.',
    universe: 'street',
    role: 'shooter',
    cost: 200,
    recharge: 12,
    hp: 500,
    attack: {
      interval: 2,
      requiresTarget: true,
      laneSpread: 2,
      projectile: { kind: 'shield', damage: 30, speed: 8, pierce: 3, ricochet: 2 },
    },
    ultimate: {
      id: 'shield_storm',
      name: 'Ricochet Rally',
      description: 'Hurls the shield through every lane, three times over.',
      duration: 3.4,
    },
    art: {
      primary: '#1b4fa0',
      secondary: '#b3202c',
      accent: '#ffffff',
      skin: '#e8b48c',
      emblem: 'star',
      head: 'mask',
      glow: '#7fb3ff',
    },
  },
  {
    id: 'nightfall',
    name: 'Nightfall',
    tagline: 'Prepared for everything, including this.',
    universe: 'nocturne',
    role: 'shooter',
    cost: 225,
    recharge: 14,
    hp: 400,
    attack: {
      interval: 1.5,
      requiresTarget: true,
      laneSpread: 1,
      hits: 'both',
      projectile: {
        kind: 'batarang',
        damage: 22,
        speed: 10,
        pierce: 2,
        hits: 'both',
        homing: true,
      },
    },
    ultimate: {
      id: 'smoke_and_steel',
      name: 'Smoke and Steel',
      description: 'Smoke bomb blinds the lane, then a batarang barrage lands.',
      duration: 4,
    },
    art: {
      primary: '#2b2f45',
      secondary: '#12141f',
      accent: '#5c6bc0',
      skin: '#e8b48c',
      emblem: 'bat',
      head: 'cowl',
      cape: true,
      glow: '#7986cb',
    },
  },
  {
    id: 'ironclad',
    name: 'Ironclad',
    tagline: 'Genius, billionaire, lane defence.',
    universe: 'metro',
    role: 'shooter',
    cost: 275,
    recharge: 18,
    hp: 450,
    attack: {
      interval: 1.8,
      requiresTarget: true,
      hits: 'both',
      projectile: {
        kind: 'blast',
        damage: 30,
        speed: 10,
        pierce: 1,
        splash: 0.8,
        hits: 'both',
      },
    },
    ultimate: {
      id: 'unibeam',
      name: 'Unibeam',
      description: 'Chest reactor opens: a sweeping beam that cooks three lanes.',
      duration: 3,
    },
    art: {
      primary: '#c62828',
      secondary: '#f0b323',
      accent: '#9fe8ff',
      skin: '#c62828',
      emblem: 'atom',
      head: 'helm',
      glow: '#ffd75e',
    },
  },
  {
    id: 'emerald_warden',
    name: 'Emerald Warden',
    tagline: 'Willpower, rendered in hard light.',
    universe: 'cosmic',
    role: 'shooter',
    cost: 275,
    recharge: 20,
    hp: 400,
    attack: {
      interval: 1.6,
      requiresTarget: true,
      laneSpread: 2,
      hits: 'both',
      projectile: {
        kind: 'construct',
        damage: 34,
        speed: 9,
        pierce: 1,
        splash: 0.6,
        hits: 'both',
        homing: true,
      },
    },
    ultimate: {
      id: 'construct_fist',
      name: 'Hard-Light Havoc',
      description: 'A giant construct fist clears the lane, then leaves a wall behind.',
      duration: 3,
    },
    art: {
      primary: '#1faa4b',
      secondary: '#0a3d1c',
      accent: '#c7ffd9',
      skin: '#e8b48c',
      emblem: 'ring',
      head: 'mask',
      glow: '#4dff87',
    },
  },
  {
    id: 'paragon',
    name: 'Paragon',
    tagline: 'Faster than the wave meter.',
    universe: 'metro',
    role: 'shooter',
    cost: 325,
    recharge: 24,
    hp: 600,
    attack: {
      interval: 2.4,
      requiresTarget: true,
      hits: 'both',
      projectile: {
        kind: 'beam',
        damage: 45,
        speed: 20,
        pierce: 99,
        hits: 'both',
        effects: [{ type: 'burn', duration: 2, power: 12 }],
      },
    },
    ultimate: {
      id: 'heat_vision',
      name: 'Heat Vision',
      description: 'Locks on and burns the entire lane clean, then freezes it solid.',
      duration: 4,
    },
    art: {
      primary: '#1552c4',
      secondary: '#b3202c',
      accent: '#ffe14d',
      skin: '#e8b48c',
      emblem: 'diamond',
      head: 'hair',
      hair: '#1b1b26',
      cape: true,
      glow: '#ff5a3c',
      scale: 1.05,
    },
  },
  {
    id: 'tempest',
    name: 'Tempest',
    tagline: 'Brings the weather with him.',
    universe: 'cosmic',
    role: 'shooter',
    cost: 325,
    recharge: 24,
    hp: 550,
    attack: {
      interval: 2.1,
      requiresTarget: true,
      laneSpread: 1,
      hits: 'both',
      projectile: {
        kind: 'spark',
        damage: 38,
        speed: 14,
        pierce: 3,
        splash: 0.7,
        hits: 'both',
        effects: [{ type: 'stun', duration: 0.5 }],
      },
    },
    ultimate: {
      id: 'thunderstorm',
      name: 'Thunderstorm',
      description: 'Calls down lightning on twelve villains anywhere on the board.',
      duration: 4,
    },
    art: {
      primary: '#8a8f98',
      secondary: '#b3202c',
      accent: '#dff3ff',
      skin: '#e8b48c',
      emblem: 'bolt',
      head: 'helm',
      cape: true,
      glow: '#bfe9ff',
      scale: 1.06,
    },
  },

  /* ---------------------------------------------------------------- *
   * Melee
   * ---------------------------------------------------------------- */
  {
    id: 'razorclaw',
    name: 'Razorclaw',
    tagline: 'Best there is at what he does. What he does is bite.',
    universe: 'street',
    role: 'melee',
    cost: 150,
    recharge: 10,
    hp: 700,
    attack: {
      interval: 0.7,
      requiresTarget: true,
      range: 1.1,
      damage: 30,
      effects: [{ type: 'burn', duration: 3, power: 8 }],
    },
    ultimate: {
      id: 'frenzy',
      name: 'Berserker Spin',
      description: 'Spins for 5 seconds, shredding everything within two cells.',
      duration: 5,
    },
    art: {
      primary: '#f0b323',
      secondary: '#1b5e20',
      accent: '#e8e8e8',
      skin: '#e8b48c',
      emblem: 'none',
      head: 'mask',
      glow: '#ffe14d',
    },
  },
  {
    id: 'rampage',
    name: 'Rampage',
    tagline: 'Anger management, weaponised.',
    universe: 'gamma',
    role: 'melee',
    cost: 250,
    recharge: 18,
    hp: 1200,
    attack: {
      interval: 2.6,
      requiresTarget: true,
      range: 1.3,
      damage: 900,
      windup: 4,
    },
    ultimate: {
      id: 'thunderclap',
      name: 'Thunderclap',
      description: 'One clap: massive damage and a board-wide shove.',
      duration: 2.5,
    },
    art: {
      primary: '#3fa34d',
      secondary: '#4b2e83',
      accent: '#a5d6a7',
      skin: '#3fa34d',
      emblem: 'fist',
      head: 'hair',
      hair: '#1d1d28',
      glow: '#7bed9f',
      scale: 1.2,
    },
  },
  {
    id: 'astraea',
    name: 'Astraea',
    tagline: 'Diplomacy first. Bracers second.',
    universe: 'cosmic',
    role: 'melee',
    cost: 275,
    recharge: 20,
    hp: 1400,
    attack: {
      interval: 1.1,
      requiresTarget: true,
      range: 1.6,
      damage: 55,
      effects: [{ type: 'slow', duration: 2, power: 0.6 }],
    },
    ultimate: {
      id: 'lasso_sweep',
      name: 'Lasso Sweep',
      description: 'Whips the lane clear and drags survivors back to the spawn line.',
      duration: 3,
    },
    art: {
      primary: '#b3202c',
      secondary: '#1552c4',
      accent: '#f0c419',
      skin: '#e8b48c',
      emblem: 'star',
      head: 'hair',
      hair: '#2a1a12',
      glow: '#ffd75e',
      scale: 1.05,
    },
  },
  {
    id: 'blur',
    name: 'Blur',
    tagline: 'Already done. Was done before you read this.',
    universe: 'metro',
    role: 'melee',
    cost: 200,
    recharge: 14,
    hp: 400,
    attack: {
      interval: 0.28,
      requiresTarget: true,
      range: 2.2,
      damage: 12,
    },
    ultimate: {
      id: 'speed_force',
      name: 'Sonic Rush',
      description: 'Runs the lane six times, hitting everything on every pass.',
      duration: 3,
    },
    art: {
      primary: '#c62828',
      secondary: '#f0c419',
      accent: '#fff3b0',
      skin: '#e8b48c',
      emblem: 'bolt',
      head: 'helm',
      glow: '#ffe14d',
    },
  },

  /* ---------------------------------------------------------------- *
   * Support & utility
   * ---------------------------------------------------------------- */
  {
    id: 'lodestone',
    name: 'Lodestone',
    tagline: 'Your helmet was never really yours.',
    universe: 'cosmic',
    role: 'support',
    cost: 100,
    recharge: 12,
    hp: 300,
    attack: {
      interval: 6,
      requiresTarget: true,
      range: 4.5,
      laneSpread: 2,
      effects: [{ type: 'strip' }],
      hits: 'both',
    },
    ultimate: {
      id: 'magnetic_purge',
      name: 'Magnetic Purge',
      description: 'Rips the armour off every villain on the board and fires it back.',
      duration: 2.5,
    },
    art: {
      primary: '#7b1fa2',
      secondary: '#b3202c',
      accent: '#e1bee7',
      skin: '#e8b48c',
      emblem: 'eye',
      head: 'helm',
      cape: true,
      glow: '#d16bff',
    },
  },
  {
    id: 'tidecaller',
    name: 'Tidecaller',
    tagline: 'Talks to fish. Also to your knees.',
    universe: 'cosmic',
    role: 'shooter',
    cost: 225,
    recharge: 14,
    hp: 600,
    attack: {
      interval: 2.2,
      requiresTarget: true,
      projectile: {
        kind: 'shard',
        damage: 26,
        speed: 8,
        pierce: 4,
        effects: [{ type: 'knockback', power: 0.7 }],
      },
    },
    ultimate: {
      id: 'tidal_wave',
      name: 'Tidal Wave',
      description: 'A wall of water sweeps the lane back to the horizon.',
      duration: 3,
    },
    art: {
      primary: '#f0a92e',
      secondary: '#1f7a4d',
      accent: '#bff0d8',
      skin: '#e8b48c',
      emblem: 'wave',
      head: 'hair',
      hair: '#f0c419',
      glow: '#5fe0b0',
    },
  },
  {
    id: 'arcanum',
    name: 'Arcanum',
    tagline: 'Reads the terms and conditions of reality.',
    universe: 'nocturne',
    role: 'support',
    cost: 250,
    recharge: 20,
    hp: 350,
    attack: {
      interval: 9,
      requiresTarget: true,
      range: 3,
      laneSpread: 1,
      hits: 'both',
      effects: [{ type: 'knockback', power: 4 }, { type: 'stun', duration: 1 }],
    },
    ultimate: {
      id: 'banishment',
      name: 'Banishment',
      description: 'Opens a gate: everything on the board is thrown back to the spawn line.',
      duration: 3,
    },
    art: {
      primary: '#1a237e',
      secondary: '#c62828',
      accent: '#ffd75e',
      skin: '#e8b48c',
      emblem: 'eye',
      head: 'hood',
      cape: true,
      glow: '#9b6bff',
    },
  },
  {
    id: 'tripwire',
    name: 'Tripwire',
    tagline: 'Caltrops. Just a lot of caltrops.',
    universe: 'nocturne',
    role: 'hazard',
    cost: 100,
    recharge: 8,
    hp: 400,
    walkable: true,
    attack: { interval: 0.5, requiresTarget: true, range: 0.6, damage: 9 },
    ultimate: {
      id: 'spike_surge',
      name: 'Spike Surge',
      description: 'Spikes erupt across the lane for heavy sustained damage.',
      duration: 5,
    },
    art: {
      primary: '#455a64',
      secondary: '#263238',
      accent: '#90a4ae',
      skin: '#455a64',
      emblem: 'none',
      head: 'bare',
      glow: '#78909c',
      scale: 0.8,
    },
  },

  /* ---------------------------------------------------------------- *
   * Instants
   * ---------------------------------------------------------------- */
  {
    id: 'fuse',
    name: 'Fuse',
    tagline: 'Arrives loud. Leaves louder.',
    universe: 'street',
    role: 'instant',
    cost: 150,
    recharge: 35,
    hp: 1,
    instant: { shape: 'square3', damage: 1800, hits: 'both' },
    art: {
      primary: '#e53935',
      secondary: '#37474f',
      accent: '#ffca28',
      skin: '#ffca28',
      emblem: 'flame',
      head: 'bare',
      glow: '#ff7043',
      scale: 0.95,
    },
  },
  {
    id: 'inferno',
    name: 'Inferno',
    tagline: 'Flame on, lane off.',
    universe: 'street',
    role: 'instant',
    cost: 175,
    recharge: 40,
    hp: 1,
    instant: {
      shape: 'lane',
      damage: 1800,
      hits: 'both',
      effects: [{ type: 'burn', duration: 3, power: 40 }],
    },
    art: {
      primary: '#ff6f00',
      secondary: '#bf360c',
      accent: '#ffe082',
      skin: '#ff8f00',
      emblem: 'flame',
      head: 'aura',
      glow: '#ff9800',
    },
  },

  /* ---------------------------------------------------------------- *
   * Summoned bodies — never appear in the picker
   * ---------------------------------------------------------------- */
  {
    id: 'emerald_wall',
    name: 'Hard-Light Wall',
    tagline: 'Will, made load-bearing.',
    universe: 'cosmic',
    role: 'defender',
    cost: 0,
    recharge: 0,
    hp: 3000,
    tall: true,
    hidden: true,
    art: {
      primary: '#1faa4b',
      secondary: '#0a3d1c',
      accent: '#c7ffd9',
      skin: '#4dff87',
      emblem: 'ring',
      head: 'aura',
      glow: '#4dff87',
      scale: 1.15,
    },
  },
];

export const HERO_BY_ID: Record<HeroId, HeroDef> = Object.fromEntries(
  HEROES.map((h) => [h.id, h]),
);

export function heroDef(id: HeroId): HeroDef {
  const def = HERO_BY_ID[id];
  if (!def) throw new Error(`Unknown hero: ${id}`);
  return def;
}

/** Unlock order for the campaign. Index 0..n is granted as levels are cleared. */
export const UNLOCK_ORDER: HeroId[] = [
  'solaris',
  'bluebolt',
  'bulwark',
  'tripwire',
  'frostbane',
  'fuse',
  'websnap',
  'trickshot',
  'adamant',
  'lodestone',
  'razorclaw',
  'sunforge',
  'voltaic',
  'vanguard',
  'blur',
  'nightfall',
  'inferno',
  'tidecaller',
  'rampage',
  'ironclad',
  'emerald_warden',
  'arcanum',
  'astraea',
  'paragon',
  'tempest',
];
