import type { VillainDef, VillainId } from '../sim/types';

/**
 * The villain roster — "zombies", in the genre's terms.
 *
 * Same rules as the heroes: original names, procedurally drawn, archetype
 * homages only. Each entry maps onto a classic lane-defence threat so the
 * gameplay loop reads instantly to anyone who has played the genre.
 */
export const VILLAINS: VillainDef[] = [
  {
    id: 'goon',
    name: 'Street Goon',
    tagline: 'Hired for the afternoon. Committed for life.',
    faction: 'street',
    hp: 190,
    speed: 0.23,
    dps: 100,
    ability: 'none',
    menace: 25,
    threat: 1,
    art: { primary: '#5c6b73', secondary: '#2f3a40', accent: '#9aa7b4', skin: '#8fa37f', head: 'goon' },
  },
  {
    id: 'riot_goon',
    name: 'Riot Goon',
    tagline: 'Brought a helmet. Feels invincible. Is not.',
    faction: 'street',
    hp: 190,
    armor: 370,
    speed: 0.23,
    dps: 100,
    ability: 'none',
    menace: 50,
    threat: 2,
    art: { primary: '#6d4c41', secondary: '#3e2723', accent: '#d7913f', skin: '#8fa37f', head: 'helm' },
  },
  {
    id: 'enforcer',
    name: 'Armoured Enforcer',
    tagline: 'Riot plating, no peripheral vision.',
    faction: 'street',
    hp: 190,
    armor: 1100,
    speed: 0.23,
    dps: 100,
    ability: 'none',
    menace: 100,
    threat: 4,
    art: { primary: '#546e7a', secondary: '#263238', accent: '#b0bec5', skin: '#8fa37f', head: 'helm' },
  },
  {
    id: 'grapnel',
    name: 'Grapnel Goon',
    tagline: 'Vaults your first line. Once.',
    faction: 'nocturne',
    hp: 500,
    speed: 0.45,
    dps: 100,
    ability: 'vault',
    menace: 75,
    threat: 3,
    art: { primary: '#37474f', secondary: '#1b2529', accent: '#ffca28', skin: '#8fa37f', head: 'hood' },
  },
  {
    id: 'shieldbearer',
    name: 'Shieldbearer',
    tagline: 'Everything from the front bounces. Everything.',
    faction: 'street',
    hp: 190,
    shield: 1100,
    speed: 0.2,
    dps: 100,
    ability: 'bulwark',
    menace: 100,
    threat: 4,
    art: { primary: '#455a64', secondary: '#212121', accent: '#8d6e63', skin: '#8fa37f', head: 'goon' },
  },
  {
    id: 'redshift',
    name: 'Redshift',
    tagline: 'Sprints the lane before you finish reading his card.',
    faction: 'metro',
    hp: 260,
    speed: 0.5,
    dps: 130,
    ability: 'none',
    menace: 100,
    threat: 4,
    art: { primary: '#ffb300', secondary: '#b71c1c', accent: '#fff59d', skin: '#8fa37f', head: 'helm', glow: '#ffd54f' },
  },
  {
    id: 'jester',
    name: 'Jester Goon',
    tagline: 'The punchline is a bomb.',
    faction: 'nocturne',
    hp: 260,
    speed: 0.3,
    dps: 100,
    ability: 'detonate',
    abilityPower: 400,
    menace: 75,
    threat: 3,
    art: { primary: '#7b1fa2', secondary: '#2e7d32', accent: '#f8bbd0', skin: '#f5f5f5', head: 'grin', glow: '#ba68c8' },
  },
  {
    id: 'aerial',
    name: 'Aerial Raider',
    tagline: 'Ground defences are somebody else’s problem.',
    faction: 'street',
    hp: 340,
    speed: 0.34,
    dps: 90,
    ability: 'flight',
    menace: 125,
    threat: 5,
    art: { primary: '#455a64', secondary: '#1b2529', accent: '#cfd8dc', skin: '#8fa37f', head: 'wings' },
  },
  {
    id: 'tunneler',
    name: 'Tunneler',
    tagline: 'Comes up behind the line. Rude.',
    faction: 'gamma',
    hp: 400,
    speed: 0.28,
    dps: 110,
    ability: 'burrow',
    menace: 125,
    threat: 5,
    art: { primary: '#795548', secondary: '#3e2723', accent: '#ffcc80', skin: '#8fa37f', head: 'helm' },
  },
  {
    id: 'coldsnap',
    name: 'Coldsnap',
    tagline: 'Freezes your best hero mid-sentence.',
    faction: 'nocturne',
    hp: 700,
    armor: 200,
    speed: 0.18,
    dps: 100,
    ability: 'chill',
    abilityPower: 7,
    menace: 150,
    threat: 6,
    art: { primary: '#4fc3f7', secondary: '#01579b', accent: '#e1f5fe', skin: '#b3e5fc', head: 'helm', glow: '#4fc3f7' },
  },
  {
    id: 'marionette',
    name: 'Marionette',
    tagline: 'Never arrives alone.',
    faction: 'nocturne',
    hp: 640,
    speed: 0.16,
    dps: 80,
    ability: 'summon',
    abilityPower: 9,
    menace: 150,
    threat: 6,
    art: { primary: '#4a148c', secondary: '#1a0033', accent: '#ffd54f', skin: '#d7ccc8', head: 'hood', glow: '#b388ff' },
  },
  {
    id: 'gunner',
    name: 'Plasma Gunner',
    tagline: 'Outranges half your roster.',
    faction: 'metro',
    hp: 480,
    armor: 200,
    speed: 0.14,
    dps: 90,
    ability: 'gunner',
    abilityPower: 3,
    menace: 150,
    threat: 6,
    art: { primary: '#37474f', secondary: '#00695c', accent: '#64ffda', skin: '#8fa37f', head: 'helm', glow: '#64ffda' },
  },
  {
    id: 'juggernought',
    name: 'Juggernought',
    tagline: 'Squashes a hero flat and keeps walking.',
    faction: 'gamma',
    hp: 3000,
    speed: 0.17,
    dps: 300,
    ability: 'crush',
    menace: 300,
    threat: 12,
    art: { primary: '#8d6e63', secondary: '#3e2723', accent: '#ffab91', skin: '#a1887f', head: 'brute', scale: 1.45 },
  },
  {
    id: 'colossus_prime',
    name: 'Colossus Prime',
    tagline: 'Crushes, then throws his sidekick over the wall.',
    faction: 'gamma',
    hp: 4200,
    speed: 0.15,
    dps: 350,
    ability: 'hurl',
    abilityPower: 0.5,
    menace: 400,
    threat: 16,
    art: { primary: '#546e7a', secondary: '#1b2529', accent: '#ff7043', skin: '#90a4ae', head: 'brute', scale: 1.5, glow: '#ff7043' },
  },
  {
    id: 'sidekick',
    name: 'Sidekick',
    tagline: 'Landed behind your line. Sorry.',
    faction: 'gamma',
    hp: 150,
    speed: 0.4,
    dps: 70,
    ability: 'none',
    menace: 25,
    threat: 1,
    art: { primary: '#8d6e63', secondary: '#3e2723', accent: '#ffab91', skin: '#a1887f', head: 'brute', scale: 0.66 },
  },

  /* ---------------------------------------------------------------- *
   * Bosses — one per world
   * ---------------------------------------------------------------- */
  {
    id: 'the_grin',
    name: 'The Grin',
    tagline: 'Rolls into Gotham in a laughing machine.',
    faction: 'nocturne',
    hp: 9000,
    speed: 0.1,
    dps: 400,
    ability: 'summon',
    abilityPower: 5,
    menace: 900,
    threat: 40,
    boss: true,
    art: { primary: '#6a1b9a', secondary: '#1b5e20', accent: '#f48fb1', skin: '#fafafa', head: 'grin', scale: 1.7, glow: '#ce93d8' },
  },
  {
    id: 'magnate',
    name: 'The Magnate',
    tagline: 'Bought Metropolis. Wants the lawn too.',
    faction: 'metro',
    hp: 11000,
    armor: 2000,
    speed: 0.1,
    dps: 420,
    ability: 'gunner',
    abilityPower: 1.8,
    menace: 1000,
    threat: 44,
    boss: true,
    art: { primary: '#2e7d32', secondary: '#4a148c', accent: '#b9f6ca', skin: '#ffe0b2', head: 'crown', scale: 1.7, glow: '#69f0ae' },
  },
  {
    id: 'colossus_omega',
    name: 'Colossus Omega',
    tagline: 'The thing the Flats were irradiated to contain.',
    faction: 'gamma',
    hp: 14000,
    armor: 2200,
    speed: 0.1,
    dps: 480,
    ability: 'hurl',
    abilityPower: 0.6,
    menace: 1200,
    threat: 52,
    boss: true,
    art: {
      primary: '#7cb342',
      secondary: '#33691e',
      accent: '#ff7043',
      skin: '#9ccc65',
      head: 'brute',
      scale: 1.8,
      glow: '#aeea00',
    },
  },
  {
    id: 'dread_tyrant',
    name: 'Dread Tyrant',
    tagline: 'Fear given a ring and a grudge.',
    faction: 'cosmic',
    hp: 13000,
    shield: 2500,
    speed: 0.11,
    dps: 450,
    ability: 'gunner',
    abilityPower: 1.5,
    menace: 1100,
    threat: 48,
    boss: true,
    art: { primary: '#fdd835', secondary: '#6a1b9a', accent: '#fff9c4', skin: '#ef9a9a', head: 'crown', scale: 1.7, glow: '#ffee58' },
  },
];

export const VILLAIN_BY_ID: Record<VillainId, VillainDef> = Object.fromEntries(
  VILLAINS.map((v) => [v.id, v]),
);

export function villainDef(id: VillainId): VillainDef {
  const def = VILLAIN_BY_ID[id];
  if (!def) throw new Error(`Unknown villain: ${id}`);
  return def;
}
